"""Initial migration

Revision ID: e534f93cfbc1
Revises: 
Create Date: 2026-04-02 15:24:22.371140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e534f93cfbc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.Column('medium', sa.String(length=255), nullable=True),
    sa.Column('disability_experience_context', sa.Text(), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=False),
    sa.Column('alt_text_description', sa.Text(), nullable=False),
    sa.Column('accessibility_notes', sa.Text(), nullable=True),
    sa.Column('artwork_image_url', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('ar_asset_url_ios', sa.Text(), nullable=True),
    sa.Column('ar_asset_url_android', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artwork_image_url', sa.Text(), nullable=False),
    sa.Column('ar_asset_url_ios', sa.Text(), nullable=True),
    sa.Column('ar_asset_url_android', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploads')
    op.drop_table('contributions')
    # ### end Alembic commands ###
